[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-surround'

### syntax

[[plugins]]
repo  = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
hook_add = '''
let g:vim_vue_plugin_config = {
      \'syntax': {
      \   'template': ['html'],
      \   'script': ['javascript'],
      \   'style': ['css'],
      \},
      \'full_syntax': [],
      \'initial_indent': [],
      \'attribute': 0,
      \'keyword': 0,
      \'foldexpr': 0,
      \'debug': 0,
      \}
'''

# [[plugins]]
# repo = 'fatih/vim-go'
# on_ft = 'go'
# hook_add = '''
# let g:go_fmt_command = "goimports"
# let g:go_def_mapping_enabled = v:false
# let g:go_doc_keywordprg_enabled = v:false
# autocmd BufWritePost *.go :GoFmt
# '''

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'

[[plugins]]
repo = 'leafOfTree/vim-vue-plugin'

[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = 'graphql'

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'

[[plugins]]
repo  = 'tpope/vim-haml'
on_ft = 'haml'

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['haml', 'slim', 'ruby', 'eruby']

[[plugins]]
repo = 'mattn/vim-gomod'
on_ft = 'gomod'

[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = 'go'
hook_add = '''
autocmd BufWritePost *.go call system('go fmt')

let g:goimports_simplify = 1

" goimport (default)
let g:goimports_cmd = 'goimports'
let g:goimports_simplify_cmd = 'go fmt'

" gofumpt
"let g:goimports_cmd = 'gofumports'
"let g:goimports_simplify_cmd = 'gofumpt'
'''

# Theme

# [[plugins]]
# repo = 'w0ng/vim-hybrid'
# hool_add = '''
#   set background=dark
#   au MyAutoCmd VimEnter * nested colorscheme hybrid
# '''
