[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

  [plugins.build]
  windows = 'tools\\update-dll-mingw'
  cygwin  = 'make -f make_cygwin.mak'
  mac     = 'make -f make_mac.mak'
  linux   = 'make'
  unix    = 'gmake'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {
    \   'colorscheme': 'wombat'
    \}
'''

#[[plugins]]
#repo = 'w0ng/vim-hybrid'
#hool_add = '''
#  set background=dark
#  au MyAutoCmd VimEnter * nested colorscheme hybrid
#'''

[[pligins]]
repo = 'dracula/vim'
hool_add = '''
  set background=dark
  au MyAutoCmd VimEnter * nested colorscheme dracula
'''
