[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'

#[[plugins]]
#repo = 'Shougo/neocomplete.vim'
#depends = 'context_filetype.vim'
#on_i = 1
#
#[[plugins]]
#repo = 'Shougo/neosnippet.vim'
#depends = ['neosnippet-snippets', 'context_filetype.vim']
#on_i = 1
#on_ft = 'snippet'
#
#[[plugins]]
#repo = 'Shougo/neosnippet-snippets'
#
#[[plugins]]
#repo = 'tpope/vim-endwise'
#on_i = 1
#
#[[plugins]]
#repo = 'tomtom/tcomment_vim'
#on_i = 1

# Syntax highlight

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown', 'md']

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_map = '<Plug>'
on_ft = 'ruby'

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = 'javascript'

# Rails

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['haml', 'ruby', 'eruby']

[[plugins]]
repo = 'basyura/unite-rails'
depends = 'unite.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

#[[plugins]]
#repo = 'w0ng/vim-hybrid'
#hool_add = '''
#  set background=dark
#  au MyAutoCmd VimEnter * nested colorscheme hybrid
#'''

[[pligins]]
repo = 'dracula/vim'
hool_add = '''
  set background=dark
  au MyAutoCmd VimEnter * nested colorscheme dracula
'''
