### syntax

[[plugins]]
repo  = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = '''
let g:go_fmt_command = "goimports"
let g:go_def_mapping_enabled = v:false
let g:go_doc_keywordprg_enabled = v:false
autocmd BufWritePost *.go :GoFmt
'''

# [[plugins]]
# repo = 'ryanolsonx/vim-lsp-javascript'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'

[[plubins]]
repo = 'ryanolsonx/vim-lsp-typescript'

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'

[[plugins]]
repo  = 'tpope/vim-haml'
on_ft = 'haml'

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['haml', 'ruby', 'eruby']


# Theme

# [[plugins]]
# repo = 'w0ng/vim-hybrid'
# hool_add = '''
#   set background=dark
#   au MyAutoCmd VimEnter * nested colorscheme hybrid
# '''
