[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_post_update = '''
  let g:quickrun_config = {'*': {'hook/time/enable': '1'},}
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
if = 'has("nvim")'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'neomake/neomake'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {
    \   'colorscheme': 'wombat'
    \}
'''

#[[plugins]]
#repo = 'w0ng/vim-hybrid'
#hool_add = '''
#  set background=dark
#  au MyAutoCmd VimEnter * nested colorscheme hybrid
#'''

[[pligins]]
repo = 'dracula/vim'
hool_add = '''
  set background=dark
  au MyAutoCmd VimEnter * nested colorscheme dracula
'''
